"""Event Bus Subscriptions Table"""

from datetime import UTC as utc_tz
from datetime import datetime

from da_vinci.core.orm.client import (
    TableClient,
    TableObject,
    TableObjectAttribute,
    TableObjectAttributeType,
    TableScanDefinition,
)


class EventBusSubscription(TableObject):
    description = "Event Bus Subscriptions"

    table_name = "da_vinci_event_bus_subscriptions"

    partition_key_attribute = TableObjectAttribute(
        "event_type",
        TableObjectAttributeType.STRING,
        description="The event type that is subscribed to",
    )

    sort_key_attribute = TableObjectAttribute(
        "function_name",
        TableObjectAttributeType.STRING,
        description="The name of the function that is subscribed to the event type",
    )

    attributes = [
        TableObjectAttribute(
            "active",
            TableObjectAttributeType.BOOLEAN,
            default=True,
            description="Whether or not the subscription is active",
        ),
        TableObjectAttribute(
            "generates_events",
            TableObjectAttributeType.STRING_LIST,
            default=[],
            description="The events generated by the subscribed function",
        ),
        TableObjectAttribute(
            "record_created",
            TableObjectAttributeType.DATETIME,
            default=lambda: datetime.now(tz=utc_tz),
            description="The date EventSubscription record was created",
        ),
        TableObjectAttribute(
            "record_last_updated",
            TableObjectAttributeType.DATETIME,
            default=lambda: datetime.now(tz=utc_tz),
            description="The date EventSubscription record was last updated",
        ),
    ]


class EventBusSubscriptionsScanDefinition(TableScanDefinition):
    def __init__(self):
        super().__init__(table_object_class=EventBusSubscription)


class EventBusSubscriptions(TableClient):
    def __init__(self, app_name: str | None = None, deployment_id: str | None = None):
        super().__init__(
            app_name=app_name,
            default_object_class=EventBusSubscription,
            deployment_id=deployment_id,
        )

    def all_active_subscriptions(self, event_type: str) -> list[EventBusSubscription]:
        """
        Return all event subscriptions for a given event type.
        """
        params = {
            "ExpressionAttributeNames": {
                "#ck": "EventType",
                "#es": "Active",
            },
            "ExpressionAttributeValues": {
                ":cv": {"S": event_type},
                ":esv": {"BOOL": True},
            },
            "FilterExpression": "#es = :esv",
            "KeyConditionExpression": "#ck = :cv",
        }

        all_items = []

        for page in self.paginated(call="query", parameters=params):
            all_items.extend(page)

        return all_items

    def delete(self, event_subscription: EventBusSubscription):
        """
        Delete an event subscription

        Keyword Arguments:
            event_subscription: The event subscription
        """

        return self.delete_object(event_subscription)

    def get(self, event_type: str, function_name: str) -> EventBusSubscription:
        """
        Return a single event subscription.

        Keyword Arguments:
            event_type: The event type.
            function_name: The function name.
        """

        return self.get_object(
            partition_key_value=event_type,
            sort_key_value=function_name,
        )

    def put(self, event_subscription: EventBusSubscription):
        """
        Create or update an event subscription.

        Keyword Arguments:
            event_subscription: The event subscription
        """

        return self.put_object(event_subscription)

    def scan(
        self, scan_definition: EventBusSubscriptionsScanDefinition
    ) -> list[EventBusSubscription]:
        """
        Return all event subscriptions.

        Keyword Arguments:
            scan_definition: The scan definition.
        """

        return self.scan_objects(scan_definition=scan_definition)
