#!/bin/bash
# Deploy documentation hosting infrastructure
# This creates the S3 bucket and CloudFront distribution for hosting docs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

STACK_NAME="${1:-da-vinci-docs}"
DOMAIN_NAME="${2:-}"
CERTIFICATE_ARN="${3:-}"

echo "Deploying documentation hosting infrastructure..."
echo "Stack Name: $STACK_NAME"

PARAMS=""
if [ -n "$DOMAIN_NAME" ]; then
    echo "Domain Name: $DOMAIN_NAME"
    PARAMS="$PARAMS ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME"
fi

if [ -n "$CERTIFICATE_ARN" ]; then
    echo "Certificate ARN: $CERTIFICATE_ARN"
    PARAMS="$PARAMS ParameterKey=CertificateArn,ParameterValue=$CERTIFICATE_ARN"
fi

# Deploy CloudFormation stack
aws cloudformation deploy \
    --stack-name "$STACK_NAME" \
    --template-file "$SCRIPT_DIR/docs-hosting.yaml" \
    ${PARAMS:+--parameter-overrides $PARAMS} \
    --capabilities CAPABILITY_IAM \
    --no-fail-on-empty-changeset

# Get outputs
echo ""
echo "Stack deployed successfully!"
echo ""
echo "Outputs:"
aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' \
    --output table

# Save outputs to environment file for easy access
BUCKET_NAME=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
    --output text)

DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
    --output text)

DOC_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`DocumentationURL`].OutputValue' \
    --output text)

cat > "$SCRIPT_DIR/docs-env.sh" <<EOF
# Documentation infrastructure environment variables
# Generated by deploy-docs-infrastructure.sh

export DOCS_S3_BUCKET="$BUCKET_NAME"
export DOCS_CLOUDFRONT_ID="$DISTRIBUTION_ID"
export DOCS_URL="$DOC_URL"
EOF

echo ""
echo "Environment variables saved to: $SCRIPT_DIR/docs-env.sh"
echo "Source this file to use: source $SCRIPT_DIR/docs-env.sh"
echo ""
echo "To deploy documentation:"
echo "  ./scripts/deploy-docs.sh <version> $BUCKET_NAME $DISTRIBUTION_ID"
